#!/bin/bash

set -eo pipefail

#
# This script starts up the test process.
#
# - Environment settings (e.g. git config) are initialized
# - Terminus plugins are installed
# - Any needed code updates are done
#
echo "Begin build for $DEFAULT_ENV. Pantheon test environment is $TERMINUS_SITE.$TERMINUS_ENV"

# Log in via Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Add pantheon git remote
git remote add pantheon ssh://codeserver.dev.853a0c69-1521-4bb0-8af2-94ed5f6f208e@codeserver.dev.853a0c69-1521-4bb0-8af2-94ed5f6f208e.drush.in:2222/~/repository.git

# Pull 
git pull pantheon $CIRCLE_BRANCH

# Push code to Pantheon
git push pantheon $CIRCLE_BRANCH

# Run updatedb on the dev environment
terminus -n env:wake "$TERMINUS_SITE.dev"
terminus -n drush $TERMINUS_SITE.dev -- updatedb --yes
terminus -n drush $TERMINUS_SITE.dev -- cc all --yes
